name: gnina-casf
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipython
  - pip

  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1
  - scikit-learn==0.24

  - matplotlib
  - seaborn

  - jinja2

  - black
  - flake8
  - mypy
  - isort